name: feeback
description: A new Flutter package for getting better feedback
version: 0.0.1
author: Jonas Uekötter
homepage: https://uekoetter.dev

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: