name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 0.1.0-beta.1
author: Jonas Uekötter
homepage: https://uekoetter.dev
repository: https://github.com/ueman/feedback

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.12.13 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: