name: feeback
description: A Flutter package for getting better feedback
version: 0.0.1-alpha
author: Jonas Uekötter
homepage: https://uekoetter.dev

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: