name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 1.0.0-nullsafety.2
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.26.0-17.5.pre'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter